name: textproc
channels:
  - conda-forge
  - bioconda
  - defaults
  - salilab
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - click=8.1.8
  - colorama=0.4.6
  - gensim=4.3.3
  - joblib=1.4.2
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libsqlite=3.48.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - nltk=3.9.1
  - numpy=1.26.4
  - openssl=3.4.1
  - pip=25.0.1
  - python=3.11.11
  - python_abi=3.11
  - readline=8.2
  - regex=2024.11.6
  - scipy=1.15.2
  - setuptools=75.8.0
  - six=1.17.0
  - smart_open=7.1.0
  - tk=8.6.13
  - tqdm=4.67.1
  - tzdata=2025a
  - wheel=0.45.1
  - wrapt=1.17.2
  - pip:
      - aniso8601==10.0.0
      - annotated-types==0.7.0
      - anyio==4.8.0
      - asttokens==3.0.0
      - black==25.1.0
      - blinker==1.9.0
      - comm==0.2.2
      - debugpy==1.8.12
      - decorator==5.1.1
      - executing==2.2.0
      - fastapi==0.115.8
      - flask==3.1.0
      - flask-marshmallow==1.3.0
      - flask-restful==0.3.10
      - flask-sqlalchemy==3.1.1
      - greenlet==3.1.1
      - h11==0.14.0
      - idna==3.10
      - ipykernel==6.29.5
      - ipython==8.32.0
      - isort==6.0.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - marshmallow-sqlalchemy==1.4.1
      - matplotlib-inline==0.1.7
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.50
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyzmq==26.2.1
      - sniffio==1.3.1
      - sqlalchemy==2.0.38
      - stack-data==0.6.3
      - starlette==0.45.3
      - tornado==6.4.2
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - uvicorn==0.34.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
